# Generated by Django 3.1.1 on 2020-09-09 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data_comentario',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 11, 4, 15, 56030, tzinfo=utc)),
        ),
    ]
