# Generated by Django 3.1.1 on 2020-09-09 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200909_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateField(default=datetime.datetime(2020, 9, 9, 11, 4, 15, 54067, tzinfo=utc), verbose_name='Data'),
        ),
    ]
